
// This file has been generated by the GUI designer. Do not modify.
namespace Colorado.Gui
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action mFileAction;
		
		private global::Gtk.Action mHelpAction;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action exitAction;
		
		private global::Gtk.Action findAction;
		
		private global::Gtk.Action aboutAction;
		
		private global::Gtk.Action importAction;
		
		private global::Gtk.Action saveAction;
		
		private global::Gtk.Action saveAsAction;
		
		private global::Gtk.Action convertAction;
		
		private global::Gtk.Action closeAction;
		
		private global::Gtk.Action propertiesAction;
		
		private global::Gtk.Action mEditAction;
		
		private global::Gtk.Action mRowsAction;
		
		private global::Gtk.Action mColumnsAction;
		
		private global::Gtk.Action removeRowsAction;
		
		private global::Gtk.Action addColumnsAction;
		
		private global::Gtk.Action removeColumnsAction;
		
		private global::Gtk.Action cleanRowAction;
		
		private global::Gtk.Action newAction;
		
		private global::Gtk.Action clearAction;
		
		private global::Gtk.Action copyRowAction;
		
		private global::Gtk.Action copyColumnAction;
		
		private global::Gtk.Action findAgainAction;
		
		private global::Gtk.Action revertToSavedAction;
		
		private global::Gtk.Action addRowsAction;
		
		private global::Gtk.Action mViewAction;
		
		private global::Gtk.ToggleAction viewToolbarAction;
		
		private global::Gtk.Action fillRowAction;
		
		private global::Gtk.Action fillColumnAction;
		
		private global::Gtk.Action insertFormulaAction;
		
		private global::Gtk.Action cleanColumnAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Toolbar tbToolBar;
		
		private global::Gtk.Entry edFind;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView tvTable;
		
		private global::Gtk.Statusbar sbStatus;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Label lblType;
		
		private global::Gtk.Label lblMeasures;
		
		private global::Gtk.VSeparator vseparator2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Colorado.Gui.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.mFileAction = new global::Gtk.Action ("mFileAction", "_File", null, null);
			this.mFileAction.ShortLabel = "_File";
			w1.Add (this.mFileAction, null);
			this.mHelpAction = new global::Gtk.Action ("mHelpAction", "_Help", null, null);
			this.mHelpAction.ShortLabel = "_Help";
			w1.Add (this.mHelpAction, null);
			this.openAction = new global::Gtk.Action ("openAction", "_Open", null, "gtk-open");
			this.openAction.ShortLabel = "_Open";
			w1.Add (this.openAction, null);
			this.exitAction = new global::Gtk.Action ("exitAction", "_Exit", null, "gtk-quit");
			this.exitAction.ShortLabel = "_Exit";
			w1.Add (this.exitAction, null);
			this.findAction = new global::Gtk.Action ("findAction", "_Find", null, "gtk-find");
			this.findAction.ShortLabel = "_Find";
			w1.Add (this.findAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", "_About", null, "gtk-about");
			this.aboutAction.ShortLabel = "_About";
			w1.Add (this.aboutAction, null);
			this.importAction = new global::Gtk.Action ("importAction", "_Import", null, "gtk-convert");
			this.importAction.ShortLabel = "_Import";
			w1.Add (this.importAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", "Save", null, "gtk-save");
			this.saveAction.ShortLabel = "Save";
			w1.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", "Save as...", null, "gtk-save-as");
			this.saveAsAction.ShortLabel = "Save as...";
			w1.Add (this.saveAsAction, null);
			this.convertAction = new global::Gtk.Action ("convertAction", "Export", null, "gtk-convert");
			this.convertAction.ShortLabel = "Export";
			w1.Add (this.convertAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", "_Close", null, "gtk-close");
			this.closeAction.ShortLabel = "_Close";
			w1.Add (this.closeAction, null);
			this.propertiesAction = new global::Gtk.Action ("propertiesAction", "_Properties", null, "gtk-properties");
			this.propertiesAction.ShortLabel = "_Properties";
			w1.Add (this.propertiesAction, "F2");
			this.mEditAction = new global::Gtk.Action ("mEditAction", "_Edit", null, null);
			this.mEditAction.ShortLabel = "_Edit";
			w1.Add (this.mEditAction, null);
			this.mRowsAction = new global::Gtk.Action ("mRowsAction", "_Rows", null, null);
			this.mRowsAction.ShortLabel = "Rows";
			w1.Add (this.mRowsAction, null);
			this.mColumnsAction = new global::Gtk.Action ("mColumnsAction", "_Columns", null, null);
			this.mColumnsAction.ShortLabel = "Columns";
			w1.Add (this.mColumnsAction, null);
			this.removeRowsAction = new global::Gtk.Action ("removeRowsAction", "_Remove rows", null, "gtk-remove");
			this.removeRowsAction.ShortLabel = "_Remove rows";
			w1.Add (this.removeRowsAction, "<Control>minus");
			this.addColumnsAction = new global::Gtk.Action ("addColumnsAction", "_Add columns", null, "gtk-add");
			this.addColumnsAction.ShortLabel = "_Insert columns";
			w1.Add (this.addColumnsAction, null);
			this.removeColumnsAction = new global::Gtk.Action ("removeColumnsAction", "_Remove columns", null, "gtk-remove");
			this.removeColumnsAction.ShortLabel = "_Remove columns";
			w1.Add (this.removeColumnsAction, null);
			this.cleanRowAction = new global::Gtk.Action ("cleanRowAction", "_Clean row", null, "gtk-clear");
			this.cleanRowAction.ShortLabel = "_Clean row";
			w1.Add (this.cleanRowAction, null);
			this.newAction = new global::Gtk.Action ("newAction", "_New", null, "gtk-new");
			this.newAction.ShortLabel = "_New";
			w1.Add (this.newAction, null);
			this.clearAction = new global::Gtk.Action ("clearAction", "_Clean row", null, "gtk-clear");
			this.clearAction.ShortLabel = "_Clean row";
			w1.Add (this.clearAction, "<Control>Delete");
			this.copyRowAction = new global::Gtk.Action ("copyRowAction", "Cop_y row", null, "gtk-goto-bottom");
			this.copyRowAction.ShortLabel = "Cop_y row";
			w1.Add (this.copyRowAction, "<Alt>c");
			this.copyColumnAction = new global::Gtk.Action ("copyColumnAction", "_Copy column", null, "gtk-goto-last");
			this.copyColumnAction.ShortLabel = "_Copy column";
			w1.Add (this.copyColumnAction, null);
			this.findAgainAction = new global::Gtk.Action ("findAgainAction", "Find _again", null, "gtk-jump-to");
			this.findAgainAction.ShortLabel = "Find _again";
			w1.Add (this.findAgainAction, "F3");
			this.revertToSavedAction = new global::Gtk.Action ("revertToSavedAction", "_Revert", null, "gtk-revert-to-saved");
			this.revertToSavedAction.ShortLabel = "_Revert";
			w1.Add (this.revertToSavedAction, null);
			this.addRowsAction = new global::Gtk.Action ("addRowsAction", "_Add rows", "Add rows", "gtk-add");
			this.addRowsAction.ShortLabel = "_Add rows";
			w1.Add (this.addRowsAction, "<Primary>plus");
			this.mViewAction = new global::Gtk.Action ("mViewAction", "_View", null, null);
			this.mViewAction.ShortLabel = "_View";
			w1.Add (this.mViewAction, null);
			this.viewToolbarAction = new global::Gtk.ToggleAction ("viewToolbarAction", "_Toolbar", null, null);
			this.viewToolbarAction.Active = true;
			this.viewToolbarAction.ShortLabel = "_Toolbar";
			w1.Add (this.viewToolbarAction, null);
			this.fillRowAction = new global::Gtk.Action ("fillRowAction", "_Fill row", null, "gtk-color-picker");
			this.fillRowAction.ShortLabel = "_Fill row";
			w1.Add (this.fillRowAction, null);
			this.fillColumnAction = new global::Gtk.Action ("fillColumnAction", "_Fill column", null, "gtk-color-picker");
			this.fillColumnAction.ShortLabel = "_Fill column";
			w1.Add (this.fillColumnAction, null);
			this.insertFormulaAction = new global::Gtk.Action ("insertFormulaAction", "_Insert formula", null, "gtk-edit");
			this.insertFormulaAction.ShortLabel = "_Insert formula";
			w1.Add (this.insertFormulaAction, null);
			this.cleanColumnAction = new global::Gtk.Action ("cleanColumnAction", "_Clean column", null, "gtk-clear");
			this.cleanColumnAction.ShortLabel = "_Clean column";
			w1.Add (this.cleanColumnAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Colorado.Gui.MainWindow";
			this.Title = "Colorado";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Colorado.Res.colorado.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Colorado.Gui.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar2\'><menu name=\'mFileAction\' action=\'mFileAction\'><menui" +
			"tem name=\'newAction\' action=\'newAction\'/><menuitem name=\'openAction\' action=\'ope" +
			"nAction\'/><menuitem name=\'saveAction\' action=\'saveAction\'/><menuitem name=\'saveA" +
			"sAction\' action=\'saveAsAction\'/><separator/><menuitem name=\'propertiesAction\' ac" +
			"tion=\'propertiesAction\'/><menuitem name=\'closeAction\' action=\'closeAction\'/><sep" +
			"arator/><menuitem name=\'revertToSavedAction\' action=\'revertToSavedAction\'/><menu" +
			"item name=\'importAction\' action=\'importAction\'/><menuitem name=\'convertAction\' a" +
			"ction=\'convertAction\'/><menuitem name=\'exitAction\' action=\'exitAction\'/></menu><" +
			"menu name=\'mEditAction\' action=\'mEditAction\'><menuitem name=\'findAction\' action=" +
			"\'findAction\'/><menuitem name=\'findAgainAction\' action=\'findAgainAction\'/><menuit" +
			"em name=\'insertFormulaAction\' action=\'insertFormulaAction\'/><separator/><menu na" +
			"me=\'mRowsAction\' action=\'mRowsAction\'><menuitem name=\'addRowsAction\' action=\'add" +
			"RowsAction\'/><menuitem name=\'removeRowsAction\' action=\'removeRowsAction\'/><menui" +
			"tem name=\'cleanRowAction\' action=\'cleanRowAction\'/><menuitem name=\'copyRowAction" +
			"\' action=\'copyRowAction\'/><menuitem name=\'fillRowAction\' action=\'fillRowAction\'/" +
			"></menu><menu name=\'mColumnsAction\' action=\'mColumnsAction\'><menuitem name=\'addC" +
			"olumnsAction\' action=\'addColumnsAction\'/><menuitem name=\'removeColumnsAction\' ac" +
			"tion=\'removeColumnsAction\'/><menuitem/><menuitem name=\'copyColumnAction\' action=" +
			"\'copyColumnAction\'/><menuitem name=\'cleanColumnAction\' action=\'cleanColumnAction" +
			"\'/><menuitem name=\'fillColumnAction\' action=\'fillColumnAction\'/></menu></menu><m" +
			"enu name=\'mViewAction\' action=\'mViewAction\'><menuitem name=\'viewToolbarAction\' a" +
			"ction=\'viewToolbarAction\'/></menu><menu name=\'mHelpAction\' action=\'mHelpAction\'>" +
			"<menuitem name=\'aboutAction\' action=\'aboutAction\'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='tbToolBar'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><separator/><toolitem name='saveAction' action='saveAction'/><toolitem name='propertiesAction' action='propertiesAction'/><toolitem name='findAction' action='findAction'/><separator/><toolitem name='addRowsAction' action='addRowsAction'/><toolitem name='removeRowsAction' action='removeRowsAction'/><toolitem name='cleanRowAction' action='cleanRowAction'/><toolitem name='copyRowAction' action='copyRowAction'/><toolitem name='fillRowAction' action='fillRowAction'/><separator/><toolitem name='addColumnsAction' action='addColumnsAction'/><toolitem name='removeColumnsAction' action='removeColumnsAction'/><toolitem/><toolitem name='cleanColumnAction' action='cleanColumnAction'/><toolitem name='copyColumnAction' action='copyColumnAction'/><toolitem name='fillColumnAction' action='fillColumnAction'/></toolbar></ui>");
			this.tbToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tbToolBar")));
			this.tbToolBar.Name = "tbToolBar";
			this.tbToolBar.ShowArrow = false;
			this.tbToolBar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.tbToolBar.IconSize = ((global::Gtk.IconSize)(3));
			this.hbox1.Add (this.tbToolBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbToolBar]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.edFind = new global::Gtk.Entry ();
			this.edFind.CanFocus = true;
			this.edFind.Name = "edFind";
			this.edFind.Text = "Find...";
			this.edFind.IsEditable = true;
			this.edFind.InvisibleChar = '●';
			this.hbox1.Add (this.edFind);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edFind]));
			w4.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvTable = new global::Gtk.TreeView ();
			this.tvTable.CanFocus = true;
			this.tvTable.Name = "tvTable";
			this.tvTable.EnableSearch = false;
			this.GtkScrolledWindow.Add (this.tvTable);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w7.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.sbStatus = new global::Gtk.Statusbar ();
			this.sbStatus.Name = "sbStatus";
			this.sbStatus.Spacing = 6;
			// Container child sbStatus.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.sbStatus.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.sbStatus [this.vseparator1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child sbStatus.Gtk.Box+BoxChild
			this.lblType = new global::Gtk.Label ();
			this.lblType.Name = "lblType";
			this.lblType.LabelProp = "\"field\", 4.5";
			this.sbStatus.Add (this.lblType);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.sbStatus [this.lblType]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child sbStatus.Gtk.Box+BoxChild
			this.lblMeasures = new global::Gtk.Label ();
			this.lblMeasures.Name = "lblMeasures";
			this.lblMeasures.LabelProp = "[10x10]";
			this.sbStatus.Add (this.lblMeasures);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.sbStatus [this.lblMeasures]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child sbStatus.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.sbStatus.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.sbStatus [this.vseparator2]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.sbStatus);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.sbStatus]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 881;
			this.DefaultHeight = 367;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpen);
			this.exitAction.Activated += new global::System.EventHandler (this.OnExit);
			this.findAction.Activated += new global::System.EventHandler (this.OnFind);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAbout);
			this.importAction.Activated += new global::System.EventHandler (this.OnImport);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSave);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAs);
			this.convertAction.Activated += new global::System.EventHandler (this.OnExport);
			this.closeAction.Activated += new global::System.EventHandler (this.OnClose);
			this.propertiesAction.Activated += new global::System.EventHandler (this.OnProperties);
			this.removeRowsAction.Activated += new global::System.EventHandler (this.OnRemoveRows);
			this.addColumnsAction.Activated += new global::System.EventHandler (this.OnAddColumns);
			this.removeColumnsAction.Activated += new global::System.EventHandler (this.OnRemoveColumns);
			this.cleanRowAction.Activated += new global::System.EventHandler (this.OnCleanRow);
			this.newAction.Activated += new global::System.EventHandler (this.OnNew);
			this.clearAction.Activated += new global::System.EventHandler (this.OnCleanRow);
			this.copyRowAction.Activated += new global::System.EventHandler (this.OnCopyRow);
			this.copyColumnAction.Activated += new global::System.EventHandler (this.OnCopyColumn);
			this.findAgainAction.Activated += new global::System.EventHandler (this.OnFindAgain);
			this.revertToSavedAction.Activated += new global::System.EventHandler (this.OnRevert);
			this.addRowsAction.Activated += new global::System.EventHandler (this.OnAddRows);
			this.viewToolbarAction.Activated += new global::System.EventHandler (this.OnViewToolbarActivated);
			this.fillRowAction.Activated += new global::System.EventHandler (this.OnFillRow);
			this.fillColumnAction.Activated += new global::System.EventHandler (this.OnFillColumn);
			this.insertFormulaAction.Activated += new global::System.EventHandler (this.OnInsertFormula);
			this.cleanColumnAction.Activated += new global::System.EventHandler (this.OnCleanColumn);
			this.edFind.EditingDone += new global::System.EventHandler (this.OnEdFindEntered);
			this.edFind.Focused += new global::Gtk.FocusedHandler (this.OnEdFindFocused);
			this.tvTable.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnTableClicked);
		}
	}
}
