
// This file has been generated by the GUI designer. Do not modify.
namespace Colorado.Gui
{
	public partial class DlgExport
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry edFileName;
		
		private global::Gtk.Button btOpen;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ComboBox cmbOutput;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.CheckButton chkIncludeTableBorder;
		
		private global::Gtk.CheckButton chkIncludeRowNumbers;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Frame frFields;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.ScrolledWindow swScroll;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Colorado.Gui.DlgExport
			this.Name = "Colorado.Gui.DlgExport";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Colorado.Gui.DlgExport.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "File";
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.edFileName = new global::Gtk.Entry ();
			this.edFileName.CanFocus = true;
			this.edFileName.Name = "edFileName";
			this.edFileName.IsEditable = false;
			this.edFileName.InvisibleChar = '●';
			this.hbox1.Add (this.edFileName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edFileName]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btOpen = new global::Gtk.Button ();
			this.btOpen.CanFocus = true;
			this.btOpen.Name = "btOpen";
			this.btOpen.UseStock = true;
			this.btOpen.UseUnderline = true;
			this.btOpen.Label = "gtk-save-as";
			this.hbox1.Add (this.btOpen);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btOpen]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "Output format";
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cmbOutput = global::Gtk.ComboBox.NewText ();
			this.cmbOutput.AppendText ("RTF");
			this.cmbOutput.AppendText ("HTML");
			this.cmbOutput.AppendText ("CSV");
			this.cmbOutput.AppendText ("XLS (MS Excel)");
			this.cmbOutput.Name = "cmbOutput";
			this.cmbOutput.Active = 0;
			this.hbox2.Add (this.cmbOutput);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cmbOutput]));
			w7.Position = 1;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.GtkAlignment4.Add (this.vbox4);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = "<b>File export</b>";
			this.GtkLabel6.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel6;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.chkIncludeTableBorder = new global::Gtk.CheckButton ();
			this.chkIncludeTableBorder.CanFocus = true;
			this.chkIncludeTableBorder.Name = "chkIncludeTableBorder";
			this.chkIncludeTableBorder.Label = "Include table _borders";
			this.chkIncludeTableBorder.DrawIndicator = true;
			this.chkIncludeTableBorder.UseUnderline = true;
			this.vbox3.Add (this.chkIncludeTableBorder);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.chkIncludeTableBorder]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.chkIncludeRowNumbers = new global::Gtk.CheckButton ();
			this.chkIncludeRowNumbers.CanFocus = true;
			this.chkIncludeRowNumbers.Name = "chkIncludeRowNumbers";
			this.chkIncludeRowNumbers.Label = "Include row _numbers";
			this.chkIncludeRowNumbers.DrawIndicator = true;
			this.chkIncludeRowNumbers.UseUnderline = true;
			this.vbox3.Add (this.chkIncludeRowNumbers);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.chkIncludeRowNumbers]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.GtkAlignment3.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = "<b>Export options</b>";
			this.GtkLabel5.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel5;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frFields = new global::Gtk.Frame ();
			this.frFields.Name = "frFields";
			this.frFields.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frFields.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.swScroll = new global::Gtk.ScrolledWindow ();
			this.swScroll.CanFocus = true;
			this.swScroll.Name = "swScroll";
			this.swScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkAlignment5.Add (this.swScroll);
			this.frFields.Add (this.GtkAlignment5);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = "<b>Fields</b>";
			this.GtkLabel7.UseMarkup = true;
			this.frFields.LabelWidget = this.GtkLabel7;
			this.vbox2.Add (this.frFields);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frFields]));
			w19.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w20.Position = 0;
			w20.Padding = ((uint)(5));
			// Internal child Colorado.Gui.DlgExport.ActionArea
			global::Gtk.HButtonBox w21 = this.ActionArea;
			w21.Name = "dialog1_ActionArea";
			w21.Spacing = 6;
			w21.BorderWidth = ((uint)(5));
			w21.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonCancel]));
			w22.Expand = false;
			w22.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonOk]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 329;
			this.Show ();
			this.btOpen.Clicked += new global::System.EventHandler (this.OnSaveAs);
			this.cmbOutput.Changed += new global::System.EventHandler (this.OnChanged);
		}
	}
}
