
// This file has been generated by the GUI designer. Do not modify.
namespace Colorado.Gui
{
	public partial class DlgImport
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label lblFile;
		
		private global::Gtk.Entry edFile;
		
		private global::Gtk.Button btOpen;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBoxEntry cmbDelimiter;
		
		private global::Gtk.CheckButton chkHeaders;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Colorado.Gui.DlgImport
			this.Name = "Colorado.Gui.DlgImport";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Colorado.Gui.DlgImport.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblFile = new global::Gtk.Label ();
			this.lblFile.Name = "lblFile";
			this.lblFile.LabelProp = "File";
			this.hbox1.Add (this.lblFile);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblFile]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.edFile = new global::Gtk.Entry ();
			this.edFile.CanFocus = true;
			this.edFile.Name = "edFile";
			this.edFile.IsEditable = false;
			this.edFile.InvisibleChar = '●';
			this.hbox1.Add (this.edFile);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edFile]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btOpen = new global::Gtk.Button ();
			this.btOpen.CanFocus = true;
			this.btOpen.Name = "btOpen";
			this.btOpen.UseStock = true;
			this.btOpen.UseUnderline = true;
			this.btOpen.Label = "gtk-open";
			this.hbox1.Add (this.btOpen);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btOpen]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.GtkAlignment3.Add (this.vbox4);
			this.frame3.Add (this.GtkAlignment3);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = "<b>File</b>";
			this.GtkLabel4.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "Delimiter";
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w9.Position = 0;
			w9.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cmbDelimiter = global::Gtk.ComboBoxEntry.NewText ();
			this.cmbDelimiter.Name = "cmbDelimiter";
			this.hbox2.Add (this.cmbDelimiter);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cmbDelimiter]));
			w10.Position = 1;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.chkHeaders = new global::Gtk.CheckButton ();
			this.chkHeaders.CanFocus = true;
			this.chkHeaders.Name = "chkHeaders";
			this.chkHeaders.Label = "First row is for headers";
			this.chkHeaders.Active = true;
			this.chkHeaders.DrawIndicator = true;
			this.chkHeaders.UseUnderline = true;
			this.vbox5.Add (this.chkHeaders);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.chkHeaders]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.GtkAlignment4.Add (this.vbox5);
			this.frame4.Add (this.GtkAlignment4);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = "<b>Options</b>";
			this.GtkLabel5.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel5;
			this.vbox2.Add (this.frame4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame4]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			w16.Padding = ((uint)(5));
			// Internal child Colorado.Gui.DlgImport.ActionArea
			global::Gtk.HButtonBox w17 = this.ActionArea;
			w17.Name = "dialog1_ActionArea";
			w17.Spacing = 6;
			w17.BorderWidth = ((uint)(5));
			w17.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w17 [this.buttonCancel]));
			w18.Expand = false;
			w18.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w17 [this.buttonOk]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 217;
			this.Show ();
			this.btOpen.Clicked += new global::System.EventHandler (this.onOpen);
		}
	}
}
